const categorys = [
    "Select categorys",
    "Action",
    "Adventure",
    "ChickLit",
    "Fanfiction",
    "Fantasy",
    "General Fiction",
    "Historical Fiction",
    "Horror",
    "Humor",
    "Mystery / Thriller",
    "Non-Fiction",
    "Paranormal",
    "Poetry",
    "Random",
    "Romance",
    "Science Fiction",
    "Short Story",
    "Spiritual",
    "Teen Fiction",
    "Vampire",
    "Werewolf"
]

const languages = [
    "Select language",
    "English",
    "Français",
    "Italiano",
    "Deutsch",
    "Español",
    "Português",
    "Català",
    "Tiếng Việt",
    "Filipino",
    "Bahasa Indonesia",
    "Bahasa Melayu",
    "ภาษาไทย",
    "Русский",
    "Română",
    "Türkçe",
    "Česky",
    "Polski",
    "Magyar",
    "ελληνικά",
    "Eesti",
    "Latviešu",
    "Lietuvių",
    "Босански",
    "Српски",
    "Hrvatski",
    "Български",
    "Slovenčina",
    "Slovenščina",
    "Беларускі",
    "Українська",
    "Svenska",
    "Norsk",
    "Suomi",
    "Dansk",
    "Nederlands",
    "Íslenska",
    "简体中文",
    "繁體中文",
    "日本語",
    "한국어",
    "العربية",
    "ગુજરાતી",
    "עברית",
    "हिन्दी",
    "മലയാളം",
    "ଓଡ଼ିଆ",
    "فارسی",
    "ਪੰਜਾਬੀ",
    "অসমীয়া",
    "বাংলা",
    "தமிழ்",
    "Kiswahili",
    "Afrikaans",
    "मराठी",
    "Other"
]

const targetAudiences = [
    "Select target audiences",
    "Young Adult (13-18 years of age)",
    "New Adult (18-25 years of age)",
    "Adult (25+ years of age)"
];

export {
    categorys, languages, targetAudiences
}